[project]
name = "letters"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.4.0",
    "matplotlib>=3.10.1",
    "torchvision>=0.21.0",
]
